version: '3'

services:
  sumak:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    init: true
    stdin_open: true
    tty: true 
    command: ["nodemon", "index.js"]